# Generated by Django 6.0.3 on 2026-03-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follows_post_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
